name: URL checks
on:
  push:
    branches:
      - gha
  schedule:
    - cron:  '0 12 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2          
    
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.2.0
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        save: "urls.csv"
        
    - name: Debug Step 
      if: always()
      run: | 
        echo "Present working directory is ${PWD}" 
        ls 
        cat urls.csv
    
    - name: Archive URL checking results
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: urlchecker-results
        path: urls.csv

